### ISSUE TITLE
Incorrect sampling when quality string starts with @

### ISSUE THREAD

**Issue by Smeds** [maaskola/samplefq#1]
When the quality string starts with a @, samplefq will interpret it incorrectly as a read header. Which results in that sampled fastq file will be invalid

The example will increase the idx counter twice, if the read isn't one of the reads that we are supposed to sample:
@HWI-D00457:105:C6T42ANXX:2:1101:6283:2160 2:N:0:AGCAGGAA
GAGCTCNNNNNNNNNNNNNNNNNNNNNNNNNACAGATTACAGCAATCANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTCTGTACAGCCCACTNNNNNNNNNNNNNNNNNGNNCNN
+
@BABBG#########################:==<FDFFFGGGDFGGG#############################################################################

Let's say that we with the quality string have a idx value that we are supposed to extract, the resulting file sampled read will look like this:

@BABBG#########################:==<FDFFFGGGDFGGG#############################################################################
@HWI-D00457:105:C6T42ANXX:2:1101:6382:2162 2:N:0:AGCAGGAA
GTGATGCNNNNNNNNNNNNNNNNNNNNNNNTCCATACCCCAGGTGAGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCAAGTAGACCTTCATCNNNNNNNNNNNNNNNNNANNCCT
+

The could be solved by either making sure that 4 rows are read each time, before comparing idx. Or by making a more rigorous check for the header, one where the quality string can't be mistaken for the read header.

**Comment by maaskola** [comment]
Thanks for reporting this issue! Commit 083dcdb2467f6c7e14b5130d5262072cfc645867 hopefully fixes it.

The logic of the commit is as you suggested: whenever a new entry is found (a line starting with a separator symbol is expected and found) that is not to be output, the subsequent lines are read and discarded. Previously, it would continue scanning for a line starting with a separator symbol.

Note that currently parsing of FASTA and FASTQ is not compatible with multi-line format variants.

Please report if the commit fixes the issue you are seeing, as it was only tested on a small example FASTQ file based on the entry you provided.

**Comment by Smeds** [comment]
It solved the issue for me. I have tested the update on multiple fastq files (each with a file size of~30G)

**Comment by maaskola** [comment]
Thanks again for reporting and the subsequent testing!

Closing this bug report.

Note: a new [issue](2) was created, addressing the need for an improved FASTQ parser.
